version: '3.8'
services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py collectstatic --no-input &&
             gunicorn core.wsgi:application --timeout 60 --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/static_files
    expose:
      - 8000
    depends_on:
      - db
      - redis
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
  db:
    image: postgres:16
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env
  redis:
    image: redis:alpine3.18
  celery:
    build: .
    command: celery -A core worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
    env_file:
      - .env
  celery-beat:
    build: .
    command: celery -A core beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
    env_file:
      - .env
  prometheus:
    image: prom/prometheus:v2.47.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus-data:/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/static_files
    ports:
      - "80:80"
    depends_on:
      - web
volumes:
  db:
    driver: local
  static_volume:
    driver: local
  prometheus-data:
    driver: local
